### ISSUE TITLE
Link the Service Teasers on main directly to their paragraph on services

### ISSUE THREAD

**Issue by milljoniaer** [satellytes/satellytes.com#294] opened 2021-12-17 13:58 UTC
It would be nice to be able to link to specific paragraphs on a page. For example with the service-teasers on the main page. They should link directly to their paragraph on services instead of linking all to the start of services.

I have tried to do this with the native browser API with fragments or hashes and an `id` added to the headlines. But somehow Gatsby adds always a `/` at the end of each link and that prevents the browser from scrolling the this part, since he then does not find the correct id.

The easiest way to do this whole might be to just use the `useAnchorTagScrolling()` just like Fabian suggested in the beginning.

**Comment by georgiee** [comment] 2022-03-21 09:34
I think this is currently addressed by the pending PR in https://github.com/satellytes/satellytes.com/pull/488

**Comment by georgiee** [comment] 2022-03-21 10:37
duplicate of https://github.com/satellytes/satellytes.com/issues/459

**Closed as completed by georgiee** 2022-03-21 10:37 UTC
Labels: change:enhancement, good first issue
